### PR TITLE
Added @Lock(LockType.READ) to ColorService

### PR DESCRIPTION
**Pull request by cchacin**

### CODE REVIEW

**Comment by jgallimore** [comment]
Hi!

Thanks for the PR! Looks like this service stores some state (color field), used by getColor() and setColor() - so I think these both need to have @Lock(LockType.WRITE). getColorObject() on the other hand could be @Lock(LockType.READ) - maybe the read lock should just be applied to that method. What do you think?

**Comment by cchacin** [comment]
Thanks @jgallimore,

WDYT about this:

```java
@Lock(READ)
@Singleton
@Path("/color")
public class ColorService {

    @Lock(WRITE)
    @Path("{color}")
    @POST
    public void setColor(@PathParam("color") String color) {
        this.color = color;
    }
}
```

**Comment by dblevins** [comment]
Looks good.  Then it can show both, which makes it a little clearer what that annotation does.

**Comment by cchacin** [comment]
@jgallimore @dblevins pushed

**Pull request merged**
