### PR TITLE
adds Gradle support.

### PR DESCRIPTION
**Pull request by lordofthejars**

### CODE REVIEW

**Comment by lordofthejars** [comment]
Now it is ready to be merged.

**Comment by lordofthejars** [comment]
Thanks for the merge :) can I contribute with other kind of tests like unit
tests, or stress tests?
El dl, 5 oct 2015 a les 20:30 David Blevins <notifications@github.com> va
escriure:

**Comment by rmannibucau** [comment]
Why not creating another project with all tests possible? Starter sounds "light" so maybe another place is more adapted, wdyt @lordofthejars ?

**Comment by lordofthejars** [comment]
well we can decide which tests add or not, for example I think that unit tests should be added here.

**Pull request merged**
